# Basic
title: tingxins
subtitle: Creep before you walk.
welcome_message: <a href="https://github.com/tingxins" target="_blank">我的开源项目</a>
description: 嘿, 我叫李昕(@tingxins), 一名 iOS 开发者, 热衷移动, 喜爱前端, 正在探索编程艺术之旅。

url: "https://tingxins.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge
markdown: kramdown

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
# blog_button:
#     title: 博客
#     description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 博客, description: 访问我的新博客地址, url: 'http://www.tingxins.cn'}
    - {title: 项目, description: 我的项目, url: 'https://github.com/tingxins'}
    - {title: 关于, description: 我的简书, url: 'http://www.jianshu.com/users/5141561e4d59/latest_articles'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: tingxins
    # duoshuo: 
    
# Social
social:
    weibo: tingxins
    github: tingxins
    twitter: tingxins
    gplus: 117623867079144396589
    mail: tingxinsss@gmail.com

# Google Analytics
ga:
    id: UA-86643638-1
    host: tingxins.com
